name: my_app
on:
  push:
  pull_request:
    branches:
      -main

jobs:
  build:
     name: Build
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checout@v3
      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
	        node-version: 16.x
      - name: Install dependencies
        run: npm i
      - name: build prpject
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with: 
	        name: production-files
          path: ./build
  deploy:
    name: deploy
    runs-on: ubuntu-latest
	  needs: build
	 
	  steps:
      - name: Download artifact
	      uses: actions/download-artifact@v2
	      with:
          name: production-files
	        path: ./build

      - name: Deploy to github pages
	      uses: peaceiris/action-gh-pages@v3
	      with:
          github_token: ${{secrets.TOKEN}} 
	        publish_dir: ./build